version: '3.6'

# https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose
# https://docs.gitlab.com/16.4/ee/install/next_steps.html
services:
  gitlab-ce:
    image: 'gitlab/gitlab-ce:16.4.1-ce.0'
    restart: always
    hostname: 'gitlab.example.com'
    container_name: gitlab-ce
    environment:
      # https://docs.gitlab.com/omnibus/settings/ssl/index.html#enable-the-lets-encrypt-integration
      # https://docs.gitlab.com/ee/administration/environment_variables.html
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['lfs_enabled'] = true
    ports:
      # https://docs.gitlab.com/ee/administration/package_information/defaults.html#ports
      - '80:80'
      - '2224:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    network_mode: bridge

volumes:
  gitlab_config:
    name: gitlab_config
  gitlab_logs:
    name: gitlab_logs
  gitlab_data:
    name: gitlab_data